$(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.downloaded:
	mkdir -p $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)
	cd $(NERVES_BUILD_DIR)/$(PACKAGE_NAME) && \
	curl -Lo $(PACKAGE_FILE) $(PACKAGE_URL)
	touch $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.downloaded

$(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.unpacked: $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.downloaded
	cd $(NERVES_BUILD_DIR)/$(PACKAGE_NAME) && \
	tar -xf $(PACKAGE_FILE)
	touch $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.unpacked

ifndef CUSTOM_BUILD

ifdef CMAKE_PARAMS
$(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.built: $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.unpacked
	cd $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/$(PACKAGE_ARCHIVE_DIR) && cmake $(CMAKE_PARAMS) .
	$(MAKE) -C $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/$(PACKAGE_ARCHIVE_DIR)
	touch $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.built
else
$(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.built: $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.unpacked
	cd $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/$(PACKAGE_ARCHIVE_DIR) && ./configure $(CONFIGURE_PARAMS)
	$(MAKE) -C $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/$(PACKAGE_ARCHIVE_DIR)
	touch $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.built
endif

$(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.installed: $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.built
	$(MAKE) -C $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/$(PACKAGE_ARCHIVE_DIR) DESTDIR=$(SYSROOT) install
	for i in $(SYSROOT)$(ENGINE_PATH)/lib/*.la; do sed -i "s~libdir='.*'~libdir='$(SYSROOT)$(ENGINE_PATH)/lib'~g" $$i; done	
	touch $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.installed
	
endif

all: $(NERVES_BUILD_DIR)/$(PACKAGE_NAME)/.installed
